language: r
sudo: required
warnings_are_errors: false

services:
  - redis-server

r_github_packages:
  - jimhester/covr
  - hadley/devtools
  - bwlewis/rredis
  - hadley/purrr
after_success:
  - Rscript -e 'covr::codecov()'
