// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fast_rbind_fill
List fast_rbind_fill(List lst);
RcppExport SEXP blink_fast_rbind_fill(SEXP lstSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type lst(lstSEXP);
    __result = Rcpp::wrap(fast_rbind_fill(lst));
    return __result;
END_RCPP
}
