# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_rbind_fill <- function(lst) {
    .Call('blink_fast_rbind_fill', PACKAGE = 'blink', lst)
}

